blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, UserUpdateView, email_verification,generate_new_password

app_name = UsersConfig.name


urlpatterns = [
    path('', LoginView.as_view(template_name="users/login.html"), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('profile/new-password', generate_new_password, name='new-password')
]

blog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class BlogEntry(models.Model):
    heading = models.CharField(max_length=200, verbose_name='заголовок')
    slug = models.CharField(max_length=100, verbose_name='slug', **NULLABLE)
    content = models.CharField(max_length=500, verbose_name='содержимое')
    image = models.ImageField(upload_to='blog/', verbose_name='превью', **NULLABLE)
    created_at = models.DateField(auto_now_add=True, verbose_name='дата создания')
    is_published = models.BooleanField(default=True, verbose_name='признак публикации')
    views_count = models.IntegerField(default=0, verbose_name='количество просмотров')

    def __str__(self):
        return f'{self.heading}'

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'

blog/views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.models import BlogEntry


class BlogCreateView(CreateView):
    model = BlogEntry
    fields = ('heading', 'content', 'image', 'is_published')
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.heading)
            new_blog.save()
        return super().form_valid(form)


class BlogListView(ListView):
    model = BlogEntry

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    model = BlogEntry

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogUpdateView(UpdateView):
    model = BlogEntry
    fields = ('heading', 'content', 'image', 'is_published')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.heading)
            new_blog.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('pk')])


class BlogDeleteView(DeleteView):
    model = BlogEntry
    success_url = reverse_lazy('blog:list')

blog/templates/blog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> Mystore</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-primary">
        <h3 class="text-light bg-primary">Меню |</h3>
        <div class="collapse navbar-collapse" id="navbarsDefault">
            {% include 'catalog/includes/base_menu.html' %}
            <div class="d-flex flex-row-reverse">
                <ul class="navbar-nav mr-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:profile' %}">Профиль</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:logout' %}">Выйти</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:login' %}">Вход</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:register' %}">Регистрация</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4"> Блог Mystore</h1>
    <p class="lead"> Блог Mystore - это отличное место для того, чтобы поделиться своими мыслями</p>
</div>

{% block content %}
{% endblock %}

{% include 'catalog/includes/footer.html' %}

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

blog/templates/blog/blogentry_confirm_delete.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="container d-flex justify-content-center">
        <div class = "text-center">
            <div class="col-12">
                <div class="row">
                    <div class="card">
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                <p>Хотите удалить блог "{{ object.heading }}"?</p>
                                <button type="submit" class="btn btn-warning">Подтвердить</button>
                                <a href="{% url 'blog:list' %}" class="btn btn-primary">Отмена</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blogentry_detail.html
{% extends 'blog/base.html' %}
{% load mymedia %}
{% block content %}
    <div class="col-12">
            <a href="{% url 'blog:list' %}" class="btn btn-primary">К блогам</a>
    </div>
    <div class="container d-flex justify-content-center">
        <div class = "text-center">
            <div class="card mb-4 box-shadow" style="max-width: 36rem;">
                <div class="card-header">
                    <h2 class="my-0 font-weight-normal">{{ object.heading }}</h2>
                </div>
                <div class="card-body">
                    <img src="{% mymedia object.image %}" alt="object.name" width="340" height="240">
                    <h3>{{ object.content }}</h3>
                    <p>{{ object.slug }}</p>
                    <h4>Просмотров {{ object.views_count }}</h4>
                    <p>Дата создания {{ object.created_at }}</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blogentry_form.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="container d-flex justify-content-center">
        <div class = "text-center">
            <div class="col-12">
                <div class="row">
                    <div class="card">
                        <div class="card-body">
                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit" class="btn btn-primary">
                                    {% if object %}
                                        Сохранить
                                    {% else %}
                                        Создать
                                    {% endif %}
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blogentry_list.html
{% extends 'blog/base.html' %}
{% block content %}
    <div class="container">
        <div class="col-12">
            <a href="{% url 'blog:create' %}" class="btn btn-lg btn-primary">Добавить материал</a>
        </div>
        <div class="row text-center">
            {% for object in object_list %}
            <div class="col-4">
                <div class="card mb-4 box-shadow my-3" style="height: 250px;">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ object.heading }}</h4>
                    </div>
                    <div class="card-body">
                        <p> {{ object.content }} </p>
                        <div class="btn-group">
                            <a href="{% url 'blog:view' object.pk %}" class="btn btn-primary mr-1">Просмотр</a>
                            <a href="{% url 'blog:edit' object.pk %}" class="btn btn-secondary mr-1">Изменение</a>
                            <a href="{% url 'blog:delete' object.pk %}" class="btn btn-warning mr-1">Удаление</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}