blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete')
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import ProductListView, ProductDetailView, ContactsView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView, CategoryListView

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='list'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('product/<int:pk>', cache_page(60)(ProductDetailView.as_view()), name='view'),
    path('create/', ProductCreateView.as_view(), name='create'),
    path('edit/<int:pk>', ProductUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', ProductDeleteView.as_view(), name='delete'),
    path('category', CategoryListView.as_view(), name='category_list')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, UserUpdateView, email_verification,generate_new_password

app_name = UsersConfig.name


urlpatterns = [
    path('', LoginView.as_view(template_name="users/login.html"), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('profile/new-password', generate_new_password, name='new-password')
]

catalog/models.py
from django.db import models

from config import settings

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='наименование')
    description = models.CharField(max_length=300, verbose_name='описание')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='наименование')
    description = models.CharField(max_length=300, verbose_name='описание')
    image = models.ImageField(upload_to='products/', verbose_name='изображение', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='категория')
    price = models.IntegerField(verbose_name='цена за покупку')
    created_at = models.DateField(auto_now_add=True, verbose_name='дата создания')
    updated_at = models.DateField(auto_now=True, verbose_name='дата последнего изменения')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='автор')
    is_published = models.BooleanField(default=False, verbose_name='признак публикации продукта')

    def __str__(self):
        return f'{self.name}: {self.description}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        permissions = [
            ('change_description', 'Can edit description'),
            ('change_category', 'Can edit category'),
            ('change_publish_status', 'Can publish product')
        ]


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукт')
    version_number = models.IntegerField(verbose_name='номер версии')
    version_name = models.CharField(max_length=100, verbose_name='имя версии')
    is_active = models.BooleanField(default=True, verbose_name='активная версия')

    def __str__(self):
        return f'{self.version_name}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms

from catalog.models import Product, Version


class StyleForMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleForMixin, forms.ModelForm):

    stop_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

    class Meta:
        model = Product
        fields = ('name', 'description', 'image', 'category', 'price')

    def clean_name(self):
        cleaned_data = self.cleaned_data.get('name')

        if cleaned_data in self.stop_words:
            raise forms.ValidationError('В названии содержатся запрещенные слова')

        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data.get('description')

        if cleaned_data in self.stop_words:
            raise forms.ValidationError('В описании содержатся запрещенные слова')

        return cleaned_data


class VersionForm(StyleForMixin, forms.ModelForm):

    class Meta:
        model = Version
        fields = '__all__'


class ProductModeratorForm(StyleForMixin, forms.ModelForm):

    class Meta:
        model = Product
        fields = ('description', 'category', 'is_published')

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView

from catalog.forms import ProductForm, VersionForm, ProductModeratorForm
from catalog.models import Product, Version, Category
from catalog.services import get_categories_from_cache


class ProductListView(ListView):
    model = Product

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        for product in context_data.get('object_list'):
            product.version = product.version_set.filter(is_active=True).first()
        return context_data

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset()
        user = self.request.user
        if not user.has_perm('catalog.change_publish_status'):
            queryset = queryset.filter(is_published=True)
        return queryset


class ContactsView(TemplateView):
    template_name = "catalog/contacts.html"

    def post(self, request, *args, **kwargs):
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'Имя: {name}\nТелефон: {phone}\n{message}')
        return HttpResponseRedirect("/contacts/")


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    login_url = reverse_lazy('users:login')


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:list')
    login_url = reverse_lazy('users:login')

    def form_valid(self, form):
        self.object = form.save()
        self.object.author = self.request.user
        self.object.save()

        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    login_url = reverse_lazy('users:login')

    def get_success_url(self):
        return reverse('catalog:edit', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = VersionFormset(self.request.POST, instance=self.object)
        else:
            formset = VersionFormset(instance=self.object)

        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)

    def get_form_class(self):
        user = self.request.user
        if user == self.object.author:
            return ProductForm
        if user.has_perm('catalog.change_publish_status'):
            return ProductModeratorForm


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:list')
    login_url = reverse_lazy('users:login')


class CategoryListView(ListView):
    model = Category

    def get_queryset(self):
        return get_categories_from_cache()

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Mystore</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <h3 class="text-light bg-dark">Меню |</h3>
        <div class="collapse navbar-collapse" id="navbarsDefault">
            {% include 'catalog/includes/base_menu.html' %}
            <div class="d-flex flex-row-reverse">
                <ul class="navbar-nav mr-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:profile' %}">Профиль</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:logout' %}">Выйти</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:login' %}">Вход</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:register' %}">Регистрация</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Mystore</h1>
    <p class="lead">Mystore - это отличный вариант для покупки различных товаров</p>
</div>

{% block content %}
{% endblock %}

{% include 'catalog/includes/footer.html' %}

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="container">
        <div class="col-12">
            <a href="{% url 'catalog:create' %}" class="btn btn-lg btn-secondary">Добавить продукт</a>
            <a href="{% url 'catalog:list' %}" class="btn btn-lg btn-secondary">К продуктам</a>
        </div>
        <div class="row text-center">
            {% for object in object_list %}
            <div class="col-4">
                <div class="card mb-4 box-shadow my-3" style="height: 200px;">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
                    </div>
                    <div class="card-body">
                        <p> {{ object.description}} </p>
                    </div>
                </div>
            </div>
            {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="container">
        <div class="row text-start">
            <div class="col-lg-8 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <table class="table table-striped">
                            <tr>
                                <td class="w-25">Страна</td>
                                <td>USA</td>
                            </tr>
                            <tr>
                                <td class="w-25">ИНН</td>
                                <td>91-1144442</td>
                            </tr>
                            <tr>
                                <td class="w-25">Адрес</td>
                                <td>Redmond,WA,98052-6399</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                    </div>
                    <div class="card-body">
                        <form method="post" action="" class="form-floating">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="name">Имя</label>
                                <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                            </div>
                            <div class="mb-3">
                                <label for="phone">Телефон</label>
                                <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                            </div>
                            <div class="mb-3">
                                <label for="message">Сообщение</label>
                                <textarea type="text" name="message" class="form-control" id="message" placeholder="Ваше сообщение" required></textarea>
                            </div>
                            <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="container">
        <div class="row text-center">
            {% for object in object_list %}
            <div class="col-4">
                <div class="card mb-4 box-shadow" style="height: 300px;">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title">{{ object.price }} руб</h1>
                        <p> {{ object.description }} </p>
                        <a href="{% url 'catalog:product' object.pk %}" class="btn btn-secondary">Описание</a>
                        <button type="button" class="btn btn-secondary">Купить</button>
                    </div>
                </div>
            </div>
            {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product.html
{% extends 'catalog/base.html' %}
{% load mymedia %}
{% block content %}
    <div class="container d-flex justify-content-center">
        <div class = "text-center">
            <div class="card mb-4 box-shadow" style="max-width: 36rem;">
                <div class="card-header">
                    <h2 class="my-0 font-weight-normal">{{ object.name }}</h2>
                </div>
                <div class="card-body">
                    <img src="{% mymedia object.image %}" alt="object.name" width="240" height="240">
                    <h1 class="card-title pricing-card-title">{{ object.price }} руб</h1>
                    <h4>Описание:</h4>
                    <p>{{ object.description }}</p>
                    <h4>Категория:</h4>
                    <p> {{ object.category }}</p>
                    <p>Дата создания {{ object.created_at }}</p>
                    <p>Дата изменения {{ object.updated_at }}</p>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container d-flex justify-content-center">
        <div class = "text-center">
            <div class="col-12">
                <div class="row">
                    <div class="card">
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                <p>Хотите удалить продукт "{{ object.name }}"?</p>
                                <button type="submit" class="btn btn-warning">Подтвердить</button>
                                <a href="{% url 'catalog:list' %}" class="btn btn-secondary">Отмена</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load mymedia %}
{% block content %}
    <div class="col-12">
            <a href="{% url 'catalog:list' %}" class="btn btn-secondary">К продуктам</a>
    </div>
    <div class="container d-flex justify-content-center">
        <div class = "text-center">
            <div class="card mb-4 box-shadow" style="max-width: 36rem;">
                <div class="card-header">
                    <h2 class="my-0 font-weight-normal">{{ object.name }}</h2>
                </div>
                <div class="card-body">
                    <img src="{% mymedia object.image %}" alt="object.name" width="240" height="240">
                    <h1 class="card-title pricing-card-title">{{ object.price }} руб</h1>
                    <h4>Описание:</h4>
                    <p>{{ object.description }}</p>
                    <h4>Категория:</h4>
                    <p> {{ object.category }}</p>
                    <p>Автор: {{ object.author | default:'Без автора' }}</p>
                    <p>Дата создания {{ object.created_at }}</p>
                    <p>Дата изменения {{ object.updated_at }}</p>
                    <button type="button" class="btn btn-lg btn-block btn-outline-secondary">Купить</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
    <a href="{% url 'catalog:list' %}" class="btn btn-lg btn-secondary">К списку продуктов</a>
</div>
<div class="container">
    <div class = "text-center">
        <form method="post" enctype="multipart/form-data">
            <div class="row">
                <div class="col-6">
                    <div class="card my-3">
                        <div class="card-header">
                            Продукт
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-secondary">
                                {% if object %}
                                    Сохранить
                                {% else %}
                                    Создать
                                {% endif %}
                            </button>
                        </div>
                    </div>
                </div>
                {% if user == product.author %}
                <div class="col-6">
                    <div class="card my-3">
                        <div class="card-header">
                            Версия
                        </div>
                        <div class="card-body">
                            {{ formset.management_form }}
                            {% for form in formset.forms %}
                                {{ form.as_p }}
                                {% if forloop.revcounter0 != 0 %}
                                    <hr>
                                {% endif%}
                            {% endfor %}
                        </div>
                    </div>
                </div>
                {% endif %}
            </div>
        </form>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="container">
        <div class="col-12">
            <a href="{% url 'catalog:create' %}" class="btn btn-lg btn-secondary">Добавить продукт</a>
            <a href="{% url 'catalog:category_list' %}" class="btn btn-lg btn-secondary">К категориям</a>
        </div>
        <div class="row text-center">
            {% for object in object_list %}
            <div class="col-4">
                <div class="card mb-4 box-shadow my-3" style="height: 350px;">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title">{{ object.price }} руб</h1>
                        <p> {{ object.description|slice:":50" }} ... </p>
                        {% if object.version %}
                            <h6>Версия:</h6>
                            <h5>{{ object.version.version_name }}</h5>
                        {% else %}
                            <p>Нет активной версии</p>
                        {% endif %}
                    </div>
                    <div class="card-footer">
                        <div class="btn-group">
                            <a href="{% url 'catalog:view' object.pk %}" class="btn btn-dark mr-1">Просмотр</a>
                            {% if user == object.author or perms.catalog.change_publish_status %}
                            <a href="{% url 'catalog:edit' object.pk %}" class="btn btn-secondary mr-1">Изменение</a>
                            <a href="{% url 'catalog:delete' object.pk %}" class="btn btn-warning mr-1">Удаление</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}